### ISSUE TITLE
Crawl error

### ISSUE THREAD

**Issue by rjphares** [wsdookadr/femtocrawl#1]
**Command**: ./bin/op.py --crawl

**Issue**:
mkdir: cannot create directory ‘warc’: File exists
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

**Comment by wsdookadr** [comment]
Hey @rjphares , thank you for the bug report, I'm having a look at it now

**Comment by wsdookadr** [comment]
Okay, I've fixed the docs to cover the missing docker-related steps.
